### ISSUE TITLE
Update packagist

### ISSUE THREAD

**Issue by marcovtwout** [crisu83/yiistrap#242]
https://packagist.org/packages/crisu83/yiistrap

Package "dev-bs3" still points to outdated information (twbs missing from require section). Could you update the package? (did you set up the packagist update hook?)

**Comment by marcovtwout** [comment]
Packagist is a few days outdated again :/

![image](https://cloud.githubusercontent.com/assets/438046/5955308/ec79f54c-a7a1-11e4-9074-8ee988f974e4.png)

**Comment by crisu83** [comment]
Force updated.

On Thu, Jan 29, 2015 at 1:45 AM, marcovtwout <notifications@github.com>
wrote:

> Packagist is a few days outdated again :/
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/438046/5955308/ec79f54c-a7a1-11e4-9074-8ee988f974e4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crisu83/yiistrap/issues/242#issuecomment-71995987>.
>



-- 
Best regards,
Christoffer Niska
Phone +1 650 575 4419
Portfolio <http://crisu83.me> · LinkedIn
<http://fi.linkedin.com/in/crisu83/> · Twitter <http://twitter.com/crisu83>
 · GitHub <http://github.com/crisu83/>
E-mail ChristofferNiska@gmail.com
