### ISSUE TITLE
Get Started: Configuration import wildcard

### ISSUE THREAD

**Issue by spiderstudio** [crisu83/yiistrap#270]
In this page  http://www.getyiistrap.com/site/started#configuration it's written
```
'import' => array(
        ...
        'bootstrap.helpers.TbHtml',
    ),
```
but in my case it works better if it's:
```
 'import' => array(
        ...
        'bootstrap.helpers.*',
    ),
```

**Comment by crisu83** [comment]
This seems to be already fixed at least in the ```bs3``` branch.
