### ISSUE TITLE
::activeRadioButtonList() 'uncheckValue' doesn't work

### ISSUE THREAD

**Issue by alagodich** [crisu83/yiistrap#271]
There was an issue https://github.com/crisu83/yiistrap/issues/167
But new solution doesn't work either

```php
$uncheckValue = isset($htmlOptions['uncheckValue']) ? TbArray::popValue('uncheckValue', $htmlOptions) : '';
$hidden = isset($uncheckValue) ? parent::hiddenField($name, $uncheckValue, $hiddenOptions) : '';
```
`$hidden` will never be `''` as `isset($uncheckValue)` will always return `true`.

Possible solutions would be to use `null` instead of `''`:
```php
$uncheckValue = isset($htmlOptions['uncheckValue']) ? TbArray::popValue('uncheckValue', $htmlOptions) : null;
$hidden = isset($uncheckValue) ? parent::hiddenField($name, $uncheckValue, $hiddenOptions) : '';
```

**Comment by velosipedist** [comment]
The problem is in popValue() helper method. isset($nullKey, $options) returns false even when array contains null value under that key. Fixing in progress

**Comment by crisu83** [comment]
```TbArray::popValue``` is basically the same as ```ArrayHelper::remove``` so maybe we could check how Yii2 does it?

**Comment by rob006** [comment]
You can use http://php.net/manual/en/function.array-key-exists.php for this.

**Comment by crisu83** [comment]
Sounds good, anyone want to submit a PR that passes the tests and we can merge the fix?

**Comment by velosipedist** [comment]
the solution is correct, CHtml::checkBox() has same idea. Just a sec...

**Comment by velosipedist** [comment]
Build passing successfully :fireworks:
