### ISSUE TITLE
Release bs3

### ISSUE THREAD

**Issue by marcovtwout** [crisu83/yiistrap#285]
Is there any planning to update master to bs3, or to make a (beta) release of this branch?

**Comment by crisu83** [comment]
I'm still not sure how many uses the ```master``` branch and how many uses the ```bs3``` branch but the only option I see is to create swap ```master``` to ```bs2``` and make the ```bs3``` branch the new ```master``` branch. Do you see any problem with this solution @marcovtwout?

**Comment by marcovtwout** [comment]
That seems like the way to go, and you could increment the major version to 2.x for the new release. bs2 will then be your previous release branch, I assume mostly used for 1.x bugfixes.

**Comment by marcovtwout** [comment]
Looking at: https://github.com/crisu83/yiistrap/branches
You could probably remove the develop and stable branches?
And maybe rename the older release branch "bs2" to "1.x" for more clarity?

**Comment by marcovtwout** [comment]
It would be great if you could solve this issue soon. Then we can include a stable yiistrap in our projects without possibly breaking it on every composer update.

**Comment by crisu83** [comment]
The problem with renaming master is that it would break for everyone else. You can always use a specific commit hash through composer to lock down your version. I know that it's not what you're looking for but it should do while we are thinking about a better alternative.

**Comment by marcovtwout** [comment]
If you rely on dev-master, it is bound to break at some point, whenever the author starts work on the next major release.

But if you really want to keep master as-is, you could also do:
- Remove `develop` (older than master anyways)
- Rename `bs3` to `develop`

And you will have:
- master (for bs2 development, set branch alias to 1.3.x)
- develop (for bs3 development, set branch alias to 2.0.x)

Development then continues on both branches, tagging releases where needed. And for starters, you could then tag develop -> 2.0.0 :)

**Comment by crisu83** [comment]
Let's do this, I'll create a ```bs2``` branch (old master) and give people using the current master some time to move to that branch (say a month). What we can do in the mean while is delete the old ```develop``` branch and branch the current ```bs3``` branch as ```develop```. Then we can create a new ```master``` branch later of that new ```develop```. How does this sound?

**Comment by marcovtwout** [comment]
Sounds good! And maybe you can already create this branch alias:
```
"extra": {
    "branch-alias": {
        "dev-develop": "2.0.x-dev"
    }
}
```

So we can already set this just once in our projects' composer.json:

`"crisu83/yiistrap": ~2.0`

(combined with `min-stability: dev` and `prefer-stable: true`, or with `@dev`)

**Comment by marcovtwout** [comment]
Hey, any chance you could get this done soon?

**Comment by marcovtwout** [comment]
An ETA is all I need, otherwise I'll have to fork and republish it myself. :/

**Comment by marcovtwout** [comment]
I guess this project is dying, I made the changes on my own fork and will maintain that one.

**Comment by crisu83** [comment]
Hello @marcovtwout I'm not sure about the future of this project, but I know that it's very useful to a lot of people. The problem is that I have almost no time to maintain it due to my other responsibilities (work, family, studies). I'm adding you as a collaborator as you have showed a big interest towards the project.

**Comment by crisu83** [comment]
This has now been done, sorry for the long delay.
