### ISSUE TITLE
bs3: RadioButtonList does not set empty text passed through htmlOptions

### ISSUE THREAD

**Issue by marcovtwout** [crisu83/yiistrap#289]
The bootstrap implementation of radioButtonList() is missing the implementation to set the 'empty' attribute: https://github.com/yiisoft/yii/blob/1.1.16/framework/web/helpers/CHtml.php#L1249

**Comment by crisu83** [comment]
Wasn't this already fixed? Please re-open if the issue remains.

**Comment by marcovtwout** [comment]
Yes, here (reference missing somehow)
https://github.com/crisu83/yiistrap/pull/290
