### ISSUE TITLE
TbListView missing sorter

### ISSUE THREAD

**Issue by marcovtwout** [crisu83/yiistrap#299]
Both on master as on bs3, the TbListView is missing the sorter from the default template:

CListView: `public $template="{summary}\n{sorter}\n{items}\n{pager}";`
TbListView: `public $template = "{items}\n<div class=\"row\"><div class=\"col-md-6\">{pager}</div><div class=\"col-md-6\">{summary}</div></div>";`

**Comment by crisu83** [comment]
You are correct, do you have any suggestion where to place it? Maybe we should have it at the top on the right?

**Comment by marcovtwout** [comment]
Yes, that would probably be a good default position. What does the default CListView do, visually?

**Comment by crisu83** [comment]
```CListView``` is not a good reference for usability but I think they place it at the top.
