### ISSUE TITLE
PHP Fatal Error – yii\base\ErrorException, Call to undefined method Yii::app()

### ISSUE THREAD

**Issue by cloudswitch** [crisu83/yiistrap#309]
Hi,

I'm using yii2 basic template, I hope it correct. Installed yiistrap with composer.

After adding 
<?php Yii::app()->bootstrap->register(); ?>
to \views\layouts\main.php

I get the follwing error:
PHP Fatal Error – yii\base\ErrorException
Call to undefined method Yii::app()

It seemed so simple to install this extension, but maybe I'm doing something wrong.

**Comment by crisu83** [comment]
Yiistrap is a Yii1 extension, and not compatible with Yii2. There is a Yiistrap2 project but it's kind of abandoned.
